Change broker
AVEVA/sample-adh-sample_libraries-python pull request #29
Opened 2023-11-30 19:38 UTC by fabiodani5450

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/Signup.py
> +    def __init__(self, id: str = None, bookmark: str = None ,name: str = None, owner: Any = None, community_id: str = None, type: Any = None, created_date: str = None, last_accessed_date: str = None,
```owner```, ```type```, and ```signup_state``` could probably be something besides ```Any```

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/CreateSignupInput.py
> +    def __init__(self, name: str = None, resource_type: Any = None, resource_ids: list[str] = None):
```resource_type``` should be of type ```ResourceType```

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/SignupResources.py
> +    def Resources(self) -> SignupResource:
Type should be ```list[Signupresource]```. Same comment applies to setter.

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/SignupResources.py
> +            result['resources'] = self.Resources
Not sure that this will work. I think you need to go through each item and call ```toDictionary()```. The same comment applies for ```fromJson()``` below, but in reverse.

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/SignupResourcesInput.py
> +            result['resourcestoAdd'] = []
it to in resourcestoAdd meant to be lower case?

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/Trustee.py
> +﻿from __future__ import annotations
Rather than redefining Trustee you should use the one in the Security folder of the library. The same comment applies for TrusteeType.

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signup/Update.py
> +class Update(Generic[T]):
I would remove the Generic stuff. I added this originally because I thought it would be nice, however, the format of the event depends on the operation so this should be handled by the user's application.

2023-12-04 21:59 UTC, cbardini commented on adh_sample_library_preview/Signups.py
> +                   value_class: type = None) -> tuple[list[Update], str]:
If you get rid of the Generic stuff mentioned above, then you should also get rid of the value_class parameter here.

2023-12-07 22:29 UTC, cbardini commented on adh_sample_library_preview/Signup/CreateSignupInput.py
> +            result['resourceType'] = self.ResourceType.name
For enums, you would typically use ```.value``` rather than ```.name```

2023-12-07 22:29 UTC, cbardini commented on adh_sample_library_preview/Signup/SignupResources.py
> +                result['resources'] = resource
This will result in resources being one resource object rather than a list of resource objects

2023-12-07 22:29 UTC, cbardini commented on adh_sample_library_preview/Signup/SignupResources.py
> +                result.Resources = resource['resources']
Same comment from above applies, but in reverse.

2023-12-07 22:29 UTC, cbardini commented on adh_sample_library_preview/Signup/Signup.py
> +from Security.Trustee import Trustee
Are you sure this works without the two dots in front of the import? I tried something similar and ran into errors when running my code.

2023-12-13 18:41 UTC, derekendres requested changes

2023-12-13 18:41 UTC, derekendres commented on adh_sample_library_preview/Signups.py
> +            '-preview/Tenants/' + self.__base_client.tenant + \
we can remove -preview already....

2023-12-21 18:45 UTC, fabiodani5450 commented on adh_sample_library_preview/Signup/Signup.py
> +from Security.Trustee import Trustee
This is a strange one. When building the library it does not show any errors and all seem to be linked properly. However when I use the library to build something else then the linkage does not work. I have changed the syntax now and it works.

2023-12-21 18:46 UTC, fabiodani5450 commented on adh_sample_library_preview/Signups.py
> +            '-preview/Tenants/' + self.__base_client.tenant + \
Great catch. Fixed.

2024-01-19 16:46 UTC, cbardini approved these changes
Changes addressed my comments. Looks good!

2024-01-19 16:54 UTC, derekendres approved these changes

2024-01-19 16:54 UTC, merged